name: Сборка документов
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Установка инструментов
        run: sudo apt install -y latexila latexila-data texlive-lang-cyrillic
      - name: Сборка всех документов
        run: sh ./compile.sh
      - name: Загрузка
        run: |
          git config --global user.name 'ediah'
          git config --global user.email '60201514+ediah@users.noreply.github.com'
          git add .
          git commit -m "Пересборка документов"
          git push
